          const menuRoutes = {
            "Dashboard": "/admin/dashboard",
            "Campaign": "/admin/campaign-details",
            "Planning Tool": "/admin/inventory",
            "Admin": "/admin/manage-user",
            "Private Marketplace": "/admin/private-marketplace",
            "Reports": "/admin/reports",
            "Exchange": "/admin/exchanges",
            "Conversion": "/admin/conversion",
            "Settings": "/admin/settings",
            "Pubmatic Report": "/admin/pubmaticreport",
            "Brands": "/admin/brands",
            // Submenu mappings
            "Manage Campaign": "/admin/campaign-details",
            "Create Campaign": "/admin/campcreate",
            "Creatives": "/admin/campcreatives",
            "Domain List": "/admin/domainlists",
            "Export Segments": "/admin/ExportList",
            "Add-On": "/admin/add-ons",
            "Inventory": "/admin/inventory",
            "Devices": "/admin/Devices",
            "Locations": "/admin/Locations",
            "Users List": "/admin/manage-user",
            "Activity Log": "/admin/activity-log",
            "System Health": "/admin/system-health",
            "Roles & Permissions": "/admin/permissions",
            "One-Time-Reports": "/admin/reports",
            "Scheduled Report": "/admin/schedulereporting",
            "Ads": "/admin/reports",
            "Conversions": "/admin/conversion",
            "Daily reporting": "/admin/reports",
            "Domains": "/admin/reports",
            "Exchanges": "/admin/exchanges",
            "Campaign Report": "/admin/reports",
            "Audience": "/admin/audience",
            "CRM Audience": "/admin/crmaudience",
            "Universal Pixel": "/admin/universalpixel",
            "Groups": "/admin/grouplist",
            "My Ads": "/admin/creatives",
            "My Audiences": "/admin/audience",
            "My Audiences (Crm)": "/admin/crmaudience",
            "My Conversions": "/admin/conversion",
            "My Pixels": "/admin/universalpixel",
            "My Groups": "/admin/grouplist",
            "Add Fund Manager": "/admin/billing-history",
            "Fund Management": "/admin/billing-history",
            "Billing History": "/admin/billing-history",
          };

          export default menuRoutes;